# Generated by Django 3.2.8 on 2021-10-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_search_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='input',
        ),
        migrations.RemoveField(
            model_name='search',
            name='output',
        ),
        migrations.RemoveField(
            model_name='search',
            name='test',
        ),
        migrations.AddField(
            model_name='search',
            name='search',
            field=models.CharField(default='Data', max_length=50),
        ),
    ]
